auto: true
safe: true
markdown: rdiscount
highlighter: true
paginate: 8
permalink: /:title

title: BeiYuu.com
url: http://yangm90.giihub.com
feed: /atom.xml
author_info: <a href="http://beiyuu.com/">BeiYuu</a>
