auto: true
safe: true
markdown: rdiscount
highlighter: true
paginate: 8
permalink: /:title

title: Yangming.com
url: http://yangm90.github.io/Blog/ 
feed: /atom.xml
author_info: <a href="http://yangm90.github.io/Blog/">ym</a>
